name: CI

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Increment version
        uses: saleweaver/version_increment_action@v1
        with:
          file_path: 'version.json'
          version_key: 'version'

      - name: Create a new GitHub release
        if: env.new_version != ''
        uses: actions/create-release@v1
        with:
          tag_name: 'v${{ env.new_version }}'
          release_name: 'v${{ env.new_version }}'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
